### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by hthetiot** [montagejs/minit#80]
```
Trace
    at process.addListener (events.js:239:17)
    at /Users/hthetiot/projects/Kaazing/src/minit/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:122:15
    at Array.filter (native)
    at load (/Users/hthetiot/projects/Kaazing/src/minit/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:120:21)
    at module.exports (/Users/hthetiot/projects/Kaazing/src/minit/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:35:5)
    at Object.Gauge (/Users/hthetiot/projects/Kaazing/src/minit/node_modules/npm/node_modules/npmlog/node_modules/gauge/index.js:66:5)
    at Object.<anonymous> (/Users/hthetiot/projects/Kaazing/src/minit/node_modules/npm/node_modules/npmlog/log.js:41:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
(node) warning: possible EventEmitter memory leak detected. 11 SIGQUIT listeners added. Use emitter.setMaxListeners() to increase limit.
```

**Comment by hthetiot** [comment]
Fix https://github.com/montagejs/minit/pull/88
